#!/bin/sh
# initramfs init

# this is the init script version
VERSION=1
sysroot="$ROOT"/sysroot
splashfile=/.splash.ctrl

# some helpers
eend() {
	local msg
	if [ "$1" = 0 ] || [ $# -lt 1 ] ; then
		echo "$last_emsg: ok." > "$ROOT"/dev/kmsg
		[ "$KOPT_quiet" = yes ] && return 0
		echo "ok."
	else
		shift
		echo "$last_emsg: failed. $*" > "$ROOT"/dev/kmsg
		if [ "$KOPT_quiet" = "yes" ]; then
			echo -n "$last_emsg "
		fi
		echo "failed. $*"
		echo "initramfs emergency recovery shell launched. Type 'exit' to continue boot"
		/bin/busybox sh
	fi
}


# Recursively resolve tty aliases like console or tty0
list_console_devices() {
	if ! [ -e "$ROOT"/sys/class/tty/$1/active ]; then
		echo $1
		return
	fi

	for dev in $(cat "$ROOT"/sys/class/tty/$1/active); do
		list_console_devices $dev
	done
}

detect_serial_consoles() {
	if [ -f "$ovl" ] || [ "$KOPT_autodetect_serial" = "no" ]; then
		return
	fi
	local n=$(awk '$7 ~ /CTS/ || $7 ~ /DSR/ { print $1 }' "$ROOT"/proc/tty/driver/serial 2>/dev/null)
	if [ -n "$n" ]; then
		echo ttyS${n%:}
	fi
	for i in "$ROOT"/sys/class/tty/*; do
		if [ -e "$i"/device ]; then
			echo ${i##*/}
		fi
	done
}

setup_inittab_console() {
	term=vt100
	# Inquire the kernel for list of console= devices
	consoles="$(for c in console $KOPT_consoles $(detect_serial_consoles); do list_console_devices $c; done)"
	for tty in $consoles; do
		# ignore tty devices that gives I/O error
		if ! stty -g -F /dev/$tty >/dev/null 2>/dev/null; then
			continue
		fi
		# do nothing if inittab already have the tty set up
		if ! grep -q "^$tty:" $sysroot/etc/inittab 2>/dev/null; then
			echo "# enable login on alternative console" \
				>> $sysroot/etc/inittab
			# Baudrate of 0 keeps settings from kernel
			echo "$tty::respawn:/sbin/getty -L 0 $tty $term" \
				>> $sysroot/etc/inittab
		fi
		if [ -e "$sysroot"/etc/securetty ] && ! grep -q -w "$tty" "$sysroot"/etc/securetty; then
			echo "$tty" >> "$sysroot"/etc/securetty
		fi
	done
}

setconsole_serial() {
	for tty in $(detect_serial_consoles); do
		# ignore tty devices that gives I/O error
		if ! stty -g -F /dev/$tty >/dev/null 2>/dev/null; then
			continue
		fi
		if [ $# -eq 0 ] && $MOCK setconsole /dev/$tty; then
			return
		fi
		for pattern in "$@"; do
			if grep -E -q "$pattern" "$ROOT/sys/class/dmi/id/modalias" 2>/dev/null; then
				$MOCK setconsole /dev/$tty && return
			fi
		done
	done
}


/bin/busybox mkdir -p \
	"$ROOT"/bin \
	"$ROOT"/sbin \
	"$ROOT"/usr/bin \
	"$ROOT"/usr/sbin \
	"$ROOT"/proc \
	"$ROOT"/sys \
	"$ROOT"/dev \
	"$sysroot" \
	"$ROOT"/media/cdrom \
	"$ROOT"/media/usb \
	"$ROOT"/tmp \
	"$ROOT"/etc \

# Spread out busybox symlinks and make them available without full path
/bin/busybox --install -s
export PATH="$PATH:/usr/bin:/bin:/usr/sbin:/sbin"

# Make sure /dev/null is a device node. If /dev/null does not exist yet, the command
# mounting the devtmpfs will create it implicitly as an file with the "2>" redirection.
# The -c check is required to deal with initramfs with pre-seeded device nodes without
# error message.
[ -c /dev/null ] || $MOCK mknod -m 666 /dev/null c 1 3

$MOCK mount -t sysfs -o noexec,nosuid,nodev sysfs /sys
$MOCK mount -t devtmpfs -o exec,nosuid,mode=0755,size=1M devtmpfs /dev 2>/dev/null \
	|| $MOCK mount -t tmpfs -o exec,nosuid,mode=0755,size=1M tmpfs /dev

# Make sure /dev/kmsg is a device node. Writing to /dev/kmsg allows the use of the
# earlyprintk kernel option to monitor early init progress. As above, the -c check
# prevents an error if the device node has already been seeded.
[ -c /dev/kmsg ] || $MOCK mknod -m 660 /dev/kmsg c 1 11

$MOCK mount -t proc -o noexec,nosuid,nodev proc /proc

# pty device nodes (later system will need it)
[ -c /dev/ptmx ] || $MOCK mknod -m 666 /dev/ptmx c 5 2
[ -d /dev/pts ] || $MOCK mkdir -m 755 /dev/pts
$MOCK mount -t devpts -o gid=5,mode=0620,noexec,nosuid devpts /dev/pts

# shared memory area (later system will need it)
mkdir -p "$ROOT"/dev/shm
$MOCK mount -t tmpfs -o nodev,nosuid,noexec shm /dev/shm

# read the kernel options. we need surve things like:
#  acpi_osi="!Windows 2006" xen-pciback.hide=(01:00.0)
set -- $(cat "$ROOT"/proc/cmdline)

myopts="BOOTIF
	autodetect_serial
	blacklist
	dasd
	debug_init
	ds
	init
	init_args
	overlaytmpfs
	overlaytmpfsflags
	quiet
	resume
	resume_offset
	root
	root_size
	rootflags
	rootdev
	rootfstype
	splash
	ssh_key
	uevent_buf_size
	usbdelay
	usrflags
	zfcp
"

for opt; do
	case "$opt" in
	s|single|1)
		SINGLEMODE=yes
		continue
		;;
	console=*)
		opt="${opt#*=}"
		KOPT_consoles="${opt%%,*} $KOPT_consoles"
		switch_root_opts="-c /dev/${opt%%,*}"
		continue
		;;
	esac

	for i in $myopts; do
		case "$opt" in
		$i=*)	eval "KOPT_${i}"='${opt#*=}';;
		$i)	eval "KOPT_${i}=yes";;
		no$i)	eval "KOPT_${i}=no";;
		esac
	done
done

case "$KOPT_autodetect_serial" in
	setconsole) setconsole_serial;;
	setconsole=*) setconsole_serial $(echo "${KOPT_autodetect_serial#setconsole=}" | tr ',' ' ');;
esac

echo "Boottrap Init $VERSION" > "$ROOT"/dev/kmsg
[ "$KOPT_quiet" = yes ] || echo "Boottrap Init $VERSION"

# enable debugging if requested
[ -n "$KOPT_debug_init" ] && set -x

# set default values
: ${KOPT_init:=/sbin/init}

# hide kernel messages
[ "$KOPT_quiet" = yes ] && dmesg -n 1

ln -s /proc/mounts "$ROOT"/etc/mtab

# check if root=... was set
if [ -n "$KOPT_rootdev" ]; then
	echo "Mounting root"

	# Create mountpoints
	mkdir -p /media/root-ro /media/root-rw $sysroot/media/root-ro \
		$sysroot/media/root-rw
	# Mount read-only underlying rootfs
	rootflags="${KOPT_rootflags:+$KOPT_rootflags,}ro"
	$MOCK mount ${KOPT_rootfstype:+-t $KOPT_rootfstype} -o $rootflags \
		$KOPT_rootdev /media/root-ro
	# Mount writable overlay tmpfs
	overlaytmpfsflags="mode=0755,${KOPT_overlaytmpfsflags:+$KOPT_overlaytmpfsflags,}rw"
	$MOCK mount -t tmpfs -o $overlaytmpfsflags root-tmpfs /media/root-rw
	# Create additional mountpoints and do the overlay mount
	mkdir -p /media/root-rw/work /media/root-rw/root
	$MOCK mount -t overlay -o \
		lowerdir=/media/root-ro,upperdir=/media/root-rw/root,workdir=/media/root-rw/work \
		overlayfs $sysroot

	eend $?

	if [ -r "$sysroot/etc/fstab" ] && [ "$KOPT_usrflags" != "disable" ]; then
		while read dev mnt fs mntopts chk; do
			if [ "$mnt" = "/usr" ]; then
				$MOCK mount -t $fs \
					-o ${KOPT_usrflags:-ro} \
					$dev $sysroot/usr
				eend $?
			fi
		done < $sysroot/etc/fstab
	fi

	cat "$ROOT"/proc/mounts 2>/dev/null | while read DEV DIR TYPE OPTS ; do
		if [ "$DIR" != "/" -a "$DIR" != "$sysroot" -a "$DIR" != "$sysroot/usr" -a -d "$DIR" ]; then
			mkdir -p $sysroot/$DIR
			$MOCK mount -o move $DIR $sysroot/$DIR
		fi
	done
	$MOCK sync
	exec switch_root $switch_root_opts $sysroot $chart_init "$KOPT_init" $KOPT_init_args
	echo "initramfs emergency recovery shell launched"
	exec /bin/busybox sh
fi


# mount tmpfs sysroot
rootflags="mode=0755"
if [ -n "$KOPT_rootflags" ]; then
	rootflags="$rootflags,$KOPT_rootflags"
fi

$MOCK mount -t tmpfs -o $rootflags tmpfs $sysroot


if [ -f $sysroot/etc/fstab ]; then
	has_fstab=1
	fstab=$sysroot/etc/fstab

	# let user override tmpfs size in fstab in apkovl
	mountopts=$(awk '$2 == "/" && $3 == "tmpfs" { print $4 }' $sysroot/etc/fstab)
	if [ -n "$mountopts" ]; then
		$MOCK mount -o remount,$mountopts $sysroot
	fi
	# relocate mounts and adjust mount options
	# this is so a generated /etc/apk/repositories will use correct
	# mount dir
fi



mkdir -p $sysroot/sys $sysroot/proc $sysroot/dev
$MOCK mount -o bind /sys $sysroot/sys
$MOCK mount -o bind /proc $sysroot/proc
$MOCK mount -o bind /dev $sysroot/dev

$MOCK umount $sysroot/sys $sysroot/proc $sysroot/dev
eend $?

# unmount ovl mount if needed
if [ -n "$ovl_unmount" ]; then
	$MOCK umount $ovl_unmount 2>/dev/null
fi


# fix inittab if alternative console
setup_inittab_console

! [ -f "$sysroot"/etc/resolv.conf ] && [ -f /etc/resolv.conf ] && \
	cp /etc/resolv.conf "$sysroot"/etc

if [ ! -x "${sysroot}${KOPT_init}" ]; then
	[ "$KOPT_splash" != "no" ] && echo exit > $sysroot/$splashfile
	echo "$KOPT_init not found in new root. Launching emergency recovery shell"
	echo "Type exit to continue boot."
	/bin/busybox sh
fi

# switch over to new root
cat "$ROOT"/proc/mounts 2>/dev/null | while read DEV DIR TYPE OPTS ; do
	if [ "$DIR" != "/" -a "$DIR" != "$sysroot" -a -d "$DIR" ]; then
		mkdir -p $sysroot/$DIR
		$MOCK mount -o move $DIR $sysroot/$DIR
	fi
done
sync

echo ""
exec switch_root $switch_root_opts $sysroot $chart_init "$KOPT_init" $KOPT_init_args

echo "initramfs emergency recovery shell launched"
exec /bin/busybox sh
reboot
